# Generated by Django 4.0.2 on 2022-02-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='user_image/'),
        ),
    ]
