# Generated by Django 4.0.2 on 2022-02-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_chat', '0002_alter_detail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='image',
            field=models.ImageField(blank=True, default='user_image/default_profile.png', null=True, upload_to='user_image/'),
        ),
    ]
