# Generated by Django 4.0.2 on 2022-02-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_chat', '0004_rename_notification_detail_unreadmessagescount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='lastMessege',
            new_name='lastMessage',
        ),
        migrations.AlterField(
            model_name='detail',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='user_image/'),
        ),
    ]
