# Generated by Django 4.0.2 on 2022-02-11 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_chat', '0005_rename_lastmessege_detail_lastmessage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='unreadMessagesCount',
            new_name='notification',
        ),
    ]
